FROM registry.access.redhat.com/ubi9/python-311@sha256:9d3578927c6168e364f963b642fb15d5c4b1224a31c11da2ae970f05708724ae

# OS Packages needs to be installed as root
USER 0

# Upgrade base packages for consistency across all arches
RUN dnf upgrade -y --refresh && dnf clean all

# Install OpenBLAS only on ppc64le
RUN if [ "$(uname -m)" = "ppc64le" ]; then \
        echo "Power architecture detected. Installing OpenBLAS..."; \
        dnf install -y openblas openblas-devel && \
        dnf clean all; \
    else \
        echo "Non-Power architecture detected. Skipping OpenBLAS install."; \
    fi

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# modify permissions to support running with a random uid
RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json

# default user
USER 1001

LABEL com.redhat.component="odh-feature-server" \
      name="odh-feature-server-rhel9" \
      description="odh-feature-server" \
      summary="odh-feature-server" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-feature-server" \
      io.k8s.description="odh-feature-server"
